# tv show downloader
sonarr:
  server:
    address: sonarr
    port: 8989
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
    naming:
      renameEpisodes: true
      replaceIllegalCharacters: true
      multiEpisodeStyle: 5
      # https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/
      standardEpisodeFormat: "{Series TitleYear} - S{season:00}E{episode:00} - {Episode
        CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo
        AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
        Group}"
      dailyEpisodeFormat: "{Series TitleYear} - {Air-Date} - {Episode CleanTitle} [{Preferred
        Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{
        Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
        Group}"
      animeEpisodeFormat: "{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000}
        - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo
        VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo
        AudioLanguages}{-Release Group}"
      seriesFolderFormat: "{Series TitleYear} [imdb-{ImdbId}]"
      seasonFolderFormat: Season {season:00}
      specialsFolderFormat: Specials
      includeSeriesTitle: false
      includeEpisodeTitle: false
      includeQuality: false
      replaceSpaces: true
      separator: " - "
      numberStyle: S{season:00}E{episode:00}
    mediamanagement:
      autoUnmonitorPreviouslyDownloadedEpisodes: false
      recycleBin: ''
      recycleBinCleanupDays: 7
      downloadPropersAndRepacks: doNotUpgrade
      createEmptySeriesFolders: false
      deleteEmptyFolders: false
      fileDate: none
      rescanAfterRefresh: always
      setPermissionsLinux: false
      chmodFolder: '755'
      chownGroup: ''
      episodeTitleRequired: always
      skipFreeSpaceCheckWhenImporting: true
      minimumFreeSpaceWhenImporting: 100
      copyUsingHardlinks: true
      importExtraFiles: true
      extraFileExtensions: srt
      enableMediaInfo: true
  downloadclient:
    - name: Transmission
      enable: true
      protocol: torrent
      priority: 1
      fields:
        - name: host
          value: transmission
        - name: port
          value: 9091
        - name: username
          value: username # BALISE_TRANSMISSION_USERNAME (do not remove this comment)
        - name: password
          value: password # BALISE_TRANSMISSION_PASSWORD (do not remove this comment)
      implementation: Transmission
      configContract: TransmissionSettings

# movie downloader
radarr:
  server:
    address: radarr
    port: 7878
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
    naming:
      renameMovies: true
      replaceIllegalCharacters: true
      colonReplacementFormat: spaceDashSpace
      # https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/
      standardMovieFormat: "{Movie CleanTitle} {(Release Year)} {imdb-{ImdbId}} {edition-{Edition Tags}} {[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}][{Mediainfo VideoCodec}]{-Release Group}"
      movieFolderFormat: "{Movie CleanTitle} ({Release Year})"
      includeQuality: false
      replaceSpaces: false
    mediamanagement:
      autoUnmonitorPreviouslyDownloadedMovies: true
      recycleBin: ''
      recycleBinCleanupDays: 7
      downloadPropersAndRepacks: doNotUpgrade
      createEmptyMovieFolders: false
      deleteEmptyFolders: false
      fileDate: none
      rescanAfterRefresh: always
      autoRenameFolders: false
      pathsDefaultStatic: false
      setPermissionsLinux: false
      chmodFolder: '755'
      chownGroup: ''
      skipFreeSpaceCheckWhenImporting: true
      minimumFreeSpaceWhenImporting: 100
      copyUsingHardlinks: true
      importExtraFiles: true
      extraFileExtensions: srt
      enableMediaInfo: true
  downloadclient:
    - name: Transmission
      enable: true
      protocol: torrent
      priority: 1
      fields:
        - name: host
          value: transmission
        - name: port
          value: 9091
        - name: username
          value: username # BALISE_TRANSMISSION_USERNAME (do not remove this comment)
        - name: password
          value: password # BALISE_TRANSMISSION_PASSWORD (do not remove this comment)
      implementation: Transmission
      configContract: TransmissionSettings

# index manager
prowlarr:
  server:
    address: prowlarr
    port: 9696
  config:
    host:
      analyticsEnabled: false
    ui:
      theme: dark
  indexer: # https://indexers.prowlarr.com/master/11/
    - name: TheRARBG
      enable: true
      priority: 1
      appProfileId: 1
      definitionName: therarbg
      implementation: Cardigann
      configContract: CardigannSettings
      fields: # What fields are needed for each indexer is a bit obscure.
        - name: definitionFile
          value: therarbg
      tags: []

  applications:
    - name: Sonarr
      syncLevel: addOnly
      implementation: Sonarr
      configContract: SonarrSettings
      fields:
        - name: prowlarrUrl
          value: http://prowlarr:9696
        - name: baseUrl
          value: http://sonarr:8989
        - name: apiKey
          value: 9bb756e37dc646ff97a20e45771c6fe7 # BALISE_SONARR_API_KEY (do not remove this comment)
    - name: Radarr
      syncLevel: addOnly
      implementation: Radarr
      configContract: RadarrSettings
      fields:
        - name: prowlarrUrl
          value: http://prowlarr:9696
        - name: baseUrl
          value: http://radarr:7878
        - name: apiKey
          value: c8ea3cf639d34540968030ea6fe31d56 # BALISE_RADARR_API_KEY (do not remove this comment)
